### ISSUE TITLE
Doesn't work on Redmine 3.3.1

### ISSUE THREAD

**Issue by igor-panassiouk** [HugoHasenbein/redmine_preview_inline#1]
Great preview plugins family! 
Work well on my test server with version 3.4.x

But unfortunately on production one with version 3.3.1 I'm receiving error opening any issue (other pages seems working):

  Rendered plugins/redmine_preview_inline/app/views/issues/_history.html.erb (396.5ms)
  Rendered issues/show.html.erb within layouts/base (476.6ms)
Completed 500 Internal Server Error in 656ms (ActiveRecord: 20.6ms)

ActionView::Template::Error (undefined method `render_private_notes_indicator' for #<#<Class:0x007ff64d8461b0>:0x007ff64d6afab8>
Did you mean?  render_project_action_links):
     5:     <h4><a href="#note-<%= journal.indice %>" class="journal-link">#<%= journal.indice %></a>
     6:     <%= avatar(journal.user, :size => "24") %>
     7:     <%= authoring journal.created_on, journal.user, :label => :label_updated_time_by %>
     8:     <%= render_private_notes_indicator(journal) %></h4>
     9: 
    10:     <% if journal.details.any? %>
    11:     <ul class="details">
  plugins/redmine_preview_inline/app/views/issues/_history.html.erb:8:in `block in _596c198be7d5a39f6a540581a8ce83bd'
  plugins/redmine_preview_inline/app/views/issues/_history.html.erb:2:in `each'
  plugins/redmine_preview_inline/app/views/issues/_history.html.erb:2:in `_596c198be7d5a39f6a540581a8ce83bd'
  app/views/issues/show.html.erb:134:in `_fd426a6902759365f06eba9fec9ae96b'
  app/controllers/issues_controller.rb:117:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:114:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
